spring:
  application:
    name: playground
  messages:
    basename: messages, errors

  config:
    import:
      - classpath:/application-database.yml
      - classpath:/application-jpa.yml
      - classpath:/application-auth.yml

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

fcm:
  project-id: playground-35617
  config-path: fcm/playground-35617-firebase-adminsdk-na6ff-bd50739ddb.json