spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  application:
    name: playground
  messages:
    basename: messages, errors

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  config:
    import:
      - classpath:/application-database.yml
      - classpath:/application-jpa.yml
      - classpath:/application-auth.yml

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

fcm:
  config-path: fcm/playground-35617-firebase-adminsdk-na6ff-bd50739ddb.json